console.log("JS LOADED");
const { jsPDF } = window.jspdf;

document.getElementById("checkBtn").addEventListener("click", () => {

  const input = document.getElementById("symptoms").value.toLowerCase();
  const resultBox = document.getElementById("result");
  const doctorBox = document.getElementById("doctors");
  const pdfBtn = document.getElementById("downloadPdf");

  if (input.trim() === "") {
    alert("Please enter symptoms");
    return;
  }

  const symptomsArr = input.split(",").map(s => s.trim());

  let disease = "General Illness";
  let severity = "Minor";
  let risk = "30%";
  let colorClass = "minor";
  let emergencyText = "";

  const critical = ["chest pain", "breathing", "heart", "unconscious", "severe bleeding", "stroke", "seizure", "high fever", "persistent vomiting", "severe abdominal pain", "loss of vision"
    , "sudden weakness", "confusion", "severe allergic reaction", "severe burns", "head injury", "poisoning", "drowning","aasthma attack"];
  const moderate = ["fever", "infection", "vomiting", "weakness", "diarrhea", "sore throat", "fatigue", "dizziness", "mild allergic reaction", "minor burns", "sprain", "fracture"];

  if (symptomsArr.some(s => critical.includes(s))) {
    severity = "Critical";
    risk = "90%";
    disease = "High Risk Condition";
    colorClass = "critical";
    emergencyText = "🚨 Seek immediate medical help!";
  } 
  else if (symptomsArr.some(s => moderate.includes(s))) {
    severity = "Moderate";
    risk = "65%";
    disease = "Possible Infection";
    colorClass = "moderate";
  }

  document.getElementById("disease").innerText = disease;
  document.getElementById("probability").innerText = risk;
  document.getElementById("severity").innerText = severity;

  resultBox.className = `result ${colorClass}`;
  resultBox.classList.remove("hidden");

  // 🔥 STEP 6: Doctor Recommendation
  doctorBox.classList.remove("hidden");
  doctorBox.innerHTML = "<h3>👨‍⚕️ Recommended Doctor / Hospital</h3>";

  if (severity === "Moderate") {
    doctorBox.innerHTML += `
      <div class="doctor-card">
        👨‍⚕️ <b>Dr. Rahul Sharma</b><br>
        General Physician<br>
        📞 9876543210<br>
        ⭐ 4.3
      </div>
    `;
  }

  if (severity === "Critical") {
    doctorBox.innerHTML += `
      <div class="doctor-card">
        🏥 <b>City Care Hospital</b><br>
        Emergency & ICU<br>
        📞 24x7 Emergency<br>
        ⭐ 4.7
      </div>
      <p class="emergency">${emergencyText}</p>
    `;
  }

  if (severity === "Minor") {
    doctorBox.innerHTML += `
      <div class="doctor-card">
        ✅ Home care recommended.<br>
        If symptoms persist, consult a physician.
      </div>
    `;
  }

  // 🔥 STEP 7: SHOW PDF BUTTON
  pdfBtn.classList.remove("hidden");

  // 🔥 STEP 7: PDF DOWNLOAD
  pdfBtn.onclick = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("SmartCare - Health Report", 20, 20);

    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleString()}`, 20, 30);

    doc.text("Symptoms:", 20, 45);
    doc.text(input, 20, 55);

    doc.text(`Predicted Disease: ${disease}`, 20, 75);
    doc.text(`Risk Score: ${risk}`, 20, 85);
    doc.text(`Severity: ${severity}`, 20, 95);

    doc.text("Recommended Action:", 20, 115);

    if (severity === "Critical") {
      doc.text("Visit nearest emergency hospital immediately.", 20, 125);
    } 
    else if (severity === "Moderate") {
      doc.text("Consult a general physician within 24–48 hours.", 20, 125);
    } 
    else {
      doc.text("Home care advised. Monitor symptoms.", 20, 125);
    }

    doc.text("— Generated by SmartCare AI", 20, 150);
    doc.save("Health_Report.pdf");
  };

  // ===============================
  // 🔥 STEP 8.1 — SAVE HISTORY
  // ===============================
  const historyRecord = {
    date: new Date().toLocaleString(),
    symptoms: symptomsArr.join(", "),
    disease,
    severity,
    risk
  };

  let history = JSON.parse(localStorage.getItem("healthHistory")) || [];
  history.push(historyRecord);
  localStorage.setItem("healthHistory", JSON.stringify(history));

  console.log("History Saved:", historyRecord);

});
